---
- name: Gather system info and ensure web group
  hosts: web
  become: yes

  tasks:
    - name: Ensure group 'web' exists
      ansible.builtin.group:
        name: web
        state: present

    - name: Run lsblk and save output
      ansible.builtin.command: lsblk
      register: lsblk_output

    - name: Run top -b -n1 and save output
      ansible.builtin.command: top -b -n1
      register: top_output

    - name: Run cat /etc/fstab and save output
      ansible.builtin.command: cat /etc/fstab
      register: fstab_output

    - name: Set facts with gathered outputs
      set_fact:
        system_monitor_data: |
          ==== LSBLK OUTPUT ====
          {{ lsblk_output.stdout }}

          ==== TOP OUTPUT ====
          {{ top_output.stdout }}

          ==== FSTAB CONTENT ====
          {{ fstab_output.stdout }}

- name: Save collected data to control node
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Write each host's system monitor data to file
      copy:
        content: "{{ hostvars[item].system_monitor_data }}"
        dest: "/tmp/system_monitor_{{ item }}.txt"
      loop: "{{ groups['web'] }}"
