- name: Collect and store system info
  hosts: web
  become: yes
  tasks:
    - name: Gather lsblk
      command: lsblk
      register: lsblk_out

    - name: Gather top
      command: top -b -n1
      register: top_out

    - name: Gather fstab
      command: cat /etc/fstab
      register: fstab_out

    - name: Combine system info
      set_fact:
        system_info: |
          ==== LSBLK ====
          {{ lsblk_out.stdout }}

          ==== TOP ====
          {{ top_out.stdout }}

          ==== FSTAB ====
          {{ fstab_out.stdout }}

    - name: Save system info on managed host
      copy:
        content: "{{ system_info }}"
        dest: "/tmp/system_monitor_{{ inventory_hostname }}.txt"

    - name: Fetch system info file to Tower
      fetch:
        src: "/tmp/system_monitor_{{ inventory_hostname }}.txt"
        dest: "./fetched_system_info/"
        flat: yes
