- hosts: ansible-test1.mahity.local
  remote_user: karan             # SSH user to connect as
  become: yes                   # enable privilege escalation
  become_user: karan            # escalate to user karan (could be root if needed)
  become_method: sudo

  tasks:
    - name: Gather facts
      ansible.builtin.setup:

    - name: Create a directory with group web
      file:
        path: /tmp/testdir
        state: directory
        mode: '2775'         # set SGID bit so new files inherit the group
        owner: karan
        group: web

    - name: Run a shell command with group web
      ansible.builtin.shell: |
        sg web -c 'touch /tmp/testdir/testfile'
