- hosts: ansible-test1.mahity.local
  remote_user: karan             # SSH user to connect as
  become: yes                    # Enable privilege escalation
  become_user: karan             # Escalate to user karan (could be root if needed)
  become_method: sudo

  tasks:
    - name: Gather facts
      ansible.builtin.setup:

    - name: Ensure group web exists
      ansible.builtin.group:
        name: web
        state: present

    - name: Create a directory with group web
      ansible.builtin.file:
        path: /tmp/testdir
        state: directory
        owner: karan
        group: web
        mode: '0755'

    - name: Run a shell command with group web
      ansible.builtin.shell: |
        sg web -c 'touch /tmp/testdir/testfile'
